[package]
name = "cubic-platform"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
cubic-render = { path = "../cubic-render" }
pollster.workspace = true
tracing.workspace = true
winit.workspace = true

[lints]
workspace = true
