[package]
name = "cubic-app"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
cubic-auth = { path = "../cubic-auth" }
cubic-core = { path = "../cubic-core" }
cubic-network = { path = "../cubic-network" }
cubic-platform = { path = "../cubic-platform" }
cubic-render = { path = "../cubic-render" }
cubic-resources = { path = "../cubic-resources" }
cubic-ui = { path = "../cubic-ui" }
cubic-version = { path = "../cubic-version" }
cubic-world = { path = "../cubic-world" }
tokio.workspace = true
time = { workspace = true, features = ["local-offset"] }
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(windows)'.dependencies]
webbrowser = "1.2.4"

[lints]
workspace = true
